"""cria usuario e evento_auditoria

Revision ID: 691521add9a0
Revises: d1a5c3e7b9f2
Create Date: 2026-07-14 19:45:56.542388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691521add9a0'
down_revision = 'd1a5c3e7b9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nome', sa.String(length=80), nullable=True),
    sa.Column('papel', sa.String(length=20), nullable=True),
    sa.Column('acao', sa.String(length=80), nullable=False),
    sa.Column('alvo_tipo', sa.String(length=40), nullable=True),
    sa.Column('alvo_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('resultado', sa.String(length=10), nullable=False),
    sa.Column('detalhe', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evento_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evento_auditoria_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_evento_auditoria_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_evento_auditoria_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    with op.batch_alter_table('evento_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_auditoria_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_evento_auditoria_criado_em'))
        batch_op.drop_index(batch_op.f('ix_evento_auditoria_acao'))

    op.drop_table('evento_auditoria')
    # ### end Alembic commands ###
